# Generated by Django 3.2 on 2021-04-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
