# Generated by Django 3.2 on 2021-04-29 20:54

import Items.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Description')),
                ('stars', models.IntegerField(verbose_name='Stars')),
                ('image', models.ImageField(upload_to=Items.utils.item_directory_path, verbose_name='Image')),
            ],
        ),
    ]
